/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ecg.reader;

import java.awt.FlowLayout;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Sanja
 */
public class TachycardiaNIR extends javax.swing.JFrame {
    private ImageIcon image1;
    /**
     * Creates new form TachycardiaNIR
     */
    public TachycardiaNIR() {
        initComponents();
    
     /*   setLayout(new FlowLayout());
    
     image1 = new ImageIcon(getClass().getResource("ir.jpg"));
    
      inputImage1=new JLabel(image1);
      add(inputImage1);*/}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNIR = new javax.swing.JLabel();
        txtAfib = new javax.swing.JLabel();
        txtAflu = new javax.swing.JLabel();
        txtMAT = new javax.swing.JLabel();
        afibTh = new javax.swing.JButton();
        aflutTh = new javax.swing.JButton();
        matTh = new javax.swing.JButton();
        image = new javax.swing.JLabel();

        txtNIR.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtNIR.setText("Tachycardia with narrow QRS complex and irregular rhythm");

        txtAfib.setText("1. Atrial fibrilation");

        txtAflu.setText("2. Variable atrial flutter");

        txtMAT.setText("3. Multifocal atrial tachycardia - M.A.T ");

        afibTh.setText("AFib therapy");
        afibTh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                afibThMouseClicked(evt);
            }
        });
        afibTh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                afibThActionPerformed(evt);
            }
        });

        aflutTh.setText("AFlutter therapy");
        aflutTh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aflutThMouseClicked(evt);
            }
        });

        matTh.setText("M.A.T therapy");
        matTh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                matThMouseClicked(evt);
            }
        });

        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ecg/reader/ir.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(135, Short.MAX_VALUE)
                .addComponent(txtNIR, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(135, 135, 135))
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtAfib, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtAflu, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMAT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(aflutTh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(afibTh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(matTh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(43, 43, 43))
            .addGroup(layout.createSequentialGroup()
                .addGap(215, 215, 215)
                .addComponent(image, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(txtNIR, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtAfib, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(afibTh))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAflu)
                    .addComponent(aflutTh))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMAT)
                    .addComponent(matTh))
                .addGap(18, 18, 18)
                .addComponent(image, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(694, 525));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void afibThActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_afibThActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_afibThActionPerformed

    private void afibThMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_afibThMouseClicked
        // TODO add your handling code here:
         JOptionPane.showMessageDialog(null,"Digoxin and anti-arrhythmics, anticoagulants and cardioversion.","Therapy",JOptionPane.PLAIN_MESSAGE);

        
    }//GEN-LAST:event_afibThMouseClicked

    private void aflutThMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aflutThMouseClicked
        // TODO add your handling code here:
         JOptionPane.showMessageDialog(null,"Digoxin and anti-arrhythmics, anticoagulants and cardioversion, catheter ablation","Therapy",JOptionPane.PLAIN_MESSAGE);

    }//GEN-LAST:event_aflutThMouseClicked

    private void matThMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_matThMouseClicked
        // TODO add your handling code here:
       JOptionPane.showMessageDialog(null,"Anti-arrhythmics, anticoagulants, Mg,K i.v ,O2 ","Therapy",JOptionPane.PLAIN_MESSAGE);

        
    }//GEN-LAST:event_matThMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TachycardiaNIR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TachycardiaNIR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TachycardiaNIR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TachycardiaNIR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TachycardiaNIR().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton afibTh;
    private javax.swing.JButton aflutTh;
    private javax.swing.JLabel image;
    private javax.swing.JButton matTh;
    private javax.swing.JLabel txtAfib;
    private javax.swing.JLabel txtAflu;
    private javax.swing.JLabel txtMAT;
    private javax.swing.JLabel txtNIR;
    // End of variables declaration//GEN-END:variables
}
